In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a+a# vector addition

array([2, 4, 6])

In [4]:
2*a

array([2, 4, 6])

In [5]:
a**2


array([1, 4, 9], dtype=int32)

In [6]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])